import type { Metadata } from "next";
import { ReactNode } from "react";
import { Geist, Geist_Mono } from "next/font/google";
import Header from "@/components/Header";
import '../styles/global.scss';
import '../styles/reset.scss';
import './layout.scss'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function getCart() {
  const res = await fetch("https://fakestoreapi.com/carts/1", {
    // cache: "no-store", // if you want real-time data; otherwise defaults to SSR cache
    next: { revalidate: 60 }, // revalidates every 60 seconds
  });

  if (!res.ok) throw new Error("Failed to fetch cart");
  return res.json();
}

export default async function RootLayout({ children }: { children: ReactNode }) {
  const cart = await getCart();
  console.log('cart--->',cart);
  return (
    <html lang="en">
      <body>
        <div className="page-container">
          <Header />
          <main className="page-content">{children}</main>
        </div>
      </body>
    </html>
  );
}
